version: '3.8'
services:
  jumbo-stores-finder:
    build: ./jumbo-stores-finder
    ports:
      - "8080:8080"
  e2e:
    build:
      context: .
      dockerfile: e2e/Dockerfile
    depends_on:
      - jumbo-stores-finder
    command: ./run-tests.sh
    volumes:
      - ./reports/surefire-reports:/tests/target/surefire-reports
      - ./reports/site:/tests/target/site 